/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test public void testRoll() {
        // Arrange
        Library sut = new Library();

        // Act
        int[] result = sut.roll(4);

        // Assert
        assertEquals(4, result.length);
    }

    @Test public void testcontainsDuplicates() {
        // Arrange
        Library sut = new Library();

        // Act
        int[] containsDuplicates = {1, 2, 3, 4, 4};
        boolean result = sut.containsDuplicates(containsDuplicates);

        // Assert
        assertTrue(result);
    }




    @Test
    public void testCalculatingAverages() {
        Library sut = new Library();
        int[] arr = {3, 4, 5,1};
        double result = sut.CalculatingAverages(arr);
        assertEquals(4.0, result, 3.25);
    }


    @Test
    public void testArrayOfArrays() {
        //Arrange
        Library sut = new Library();
        int[][] arr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        // Act
        int[] result = sut.arrayOfArrays(arr);

        double lowestAvg = sut.CalculatingAverages(result);

        for (int[] subArray : arr) {
            double avg = sut.CalculatingAverages(subArray);
            assertTrue(lowestAvg <= avg);
        }
    }

}



