/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;



public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        int[] rollDice = roll(4);


        for (int roll : rollDice) {
            System.out.print(roll + " ");
        }

       boolean containsDuplicates= containsDuplicates(rollDice);
        System.out.println(containsDuplicates);


        double averages=CalculatingAverages(rollDice);
        System.out.println(averages);

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };



        int [] arrOfArrs=arrayOfArrays(weeklyMonthTemperatures);
        for (int element : arrOfArrs) {
            System.out.print(element + " ");}
    }


    public static int[] roll(int n) {
        int[] rollArr = new int[n];

        for (int i = 0; i < n; i++) {
            double randomNum = Math.random() * 6 + 1;

            rollArr[i] = (int) randomNum;

        }
        return rollArr;

    }


    public static boolean containsDuplicates(int[] arr) {
        for (int i = 0; i < arr.length; i++) {
            for (int j = i + 1; j < arr.length; j++) {
                if (arr[i] == arr[j]) {
                    return true;
                }
            }
        }
        return false;
    }

    public static double CalculatingAverages(int[] arr) {
        int sum = 0;
        for (int i = 0; i < arr.length; i++) {
            sum += arr[i];
        }
        double avg = (double) sum / arr.length;
        return avg;
    }


  public static int[] arrayOfArrays (int[][] arr){
        int [] lowestAvgArr= arr[0];
      double lowestAvg= CalculatingAverages(arr[0]);
        for (int i=0; i<arr.length ;i++){

            if (CalculatingAverages(arr[i])<=lowestAvg ){
                lowestAvg= CalculatingAverages(arr[i]);
                lowestAvgArr=arr[i];

            }

        }
        return lowestAvgArr;
  }



}
