/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("new Restaurant", 3, 20.0);
        Review review = new Review("Delicious !", "ghofran", 5, restaurant);
        restaurant.addReview("good ", "ali", 3);
        restaurant.addReview("very good", "ahmad", 4);
        System.out.println(review);
    }
}

